### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by unixorn** [okapia/zsh-viexchange#2]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license file.

Please add a license file - if you don't have one in mind,  I recommend using [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.

Thanks!

**Comment by okapia** [comment]
I've now done this.

I've used the ISC licence because it is about the most minimal and simple proper licence. If in future anyone needs it under something else like the Zsh licence then let me know.

**Comment by unixorn** [comment]
Thanks!
